/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import Room from './models/Room.gltf'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(Room)
  useFrame(state => {
    const time = state.clock.getElapsedTime();
    group.current.position.y = group.current.position.y + Math.sin(time * 2) / 100;
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.treeIsland.geometry} material={materials['Material.001']} position={[-0.1, -1.67, 3.22]} rotation={[0, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/Room.gltf')
